--- 
title: "CMSC 208 Final Project"
author: "Yi Lu, Shiyi Yang"
date: "`r format(Sys.time(), '%B %d, %Y %H:%M %Z')`"
site: bookdown::bookdown_site
bibliography: references.bib
biblio-style: apalike
link-citations: yes
---

# Overview {-}

This overview provides a brief explanation of this book. This book has two main sections, DataCamp and Econometrics. Each is described below.  

The DataCamp section is notes on DataCamp courses. Much of the content in these chapters is directly copy/pasted from DataCamp. Typically this is plagiarism, something important to avoid both at and outside of Lawrence. However, directly copy/pasted content is an important aspect of this BP and it isn't feasible to put quotation marks around all of it. So, we will give credit where credit is due here. Let this sentence serve as attribution and citation: except for the portions of the DataCamp section that are my own notes supplementing the DataCamp content, which are indicated in red font using the "mynotes" html tag, all content comes directly from [DataCamp](https://www.datacamp.com) and the author of this book is giving them credit for their content. 

Note that the first two chapters are included as examples to give you an idea of what to do.

The Econometric section has chapters based on econometrics content covered in class. Content and data in those sections come from the sources discussed in those chapters. These chapters serve as a reference for important concepts and technical skills, as well as examples of how to implement them in R. 

The first file in bookdown is always index.rmd (and the resulting output file, index.html, is the first file GitHub pages will display). Thus, this must be the first file of your book. This file has this overview and the General Notes section that follows (and initially there are brief instructions, but those are deleted once they are no longer needed).



